### ISSUE TITLE
RFP: use typescript instead of plain JS

### ISSUE THREAD

**Issue by KarimDaghari** [tunpl/programmers.tn#10]
The project in its current state (using js) is good enough for a one-person band, but as more get to interact with the code the presence of a typing system (while not to be considered a substitute for the onboarding process) eases both the onboarding and the contribution process especially so for experienced devs.

The only downside I see is that it'll have a steeper curve for inexperienced folks but I'd argue that with the choice of a react-based stack that's a non-issue (pun unintended) as react itself already requires an intermediate level to actually understand what you're doing.

I'd happily take care of converting the project to TS myself.

**Comment by elfalehdev** [comment]
The site in its current state is not something I'm actually proud of, We're working on a new design which will be integrated soon enough. And we can start with TS on it. I didn't bother myself converting the plain JS code as you said into Typescript cause I had no intention of keeping it as it is right now.

**Comment by KarimDaghari** [comment]
Cool.
